# [uatwebservers]
# 172.31.29.75 ansible_ssh_user='ec2-user'
# 172.31.28.159 ansible_ssh_user='ec2-user'
 


# [db]
# 172.31.93.3 ansible_ssh_user='ec2-user'

[lb]
172.31.86.244 ansible_ssh_user='ec2-user'


